spring:
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017/patientDB?retryWrites=true&w=majority&authSource=admin
      database: patientDB
      auto-index-creation: true
      authentication-database: admin
  application:
    name: patient-service

server:
  port: 9090